# Generated by Django 3.0.8 on 2020-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('start_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
