# Generated by Django 3.0.8 on 2020-08-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitems',
            old_name='close_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='auctionitems',
            old_name='description',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='auctionitems',
            name='start_date',
        ),
    ]
