# Generated by Django 3.0.8 on 2020-08-05 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200804_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='description',
            field=models.CharField(default=2, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 11, 18, 16, 436397)),
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
