# Generated by Django 3.0.8 on 2020-08-05 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200805_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 14, 4, 53, 509035, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
