# Generated by Django 3.0.8 on 2020-08-05 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200805_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='category',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 15, 10, 17, 720490, tzinfo=utc)),
        ),
    ]
