# Generated by Django 3.0.8 on 2020-08-05 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200805_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 15, 49, 30, 124462, tzinfo=utc)),
        ),
    ]
