# Generated by Django 3.0.8 on 2020-08-06 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200805_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=400)),
                ('image', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 12, 42, 34, 896432, tzinfo=utc)),
        ),
    ]
