# Generated by Django 3.0.8 on 2020-08-06 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200806_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 17, 29, 38, 435475, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
