# Generated by Django 3.0.8 on 2020-08-06 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200806_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 17, 36, 20, 935611, tzinfo=utc)),
        ),
    ]
