# Generated by Django 3.0.8 on 2020-08-07 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200806_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitems',
            name='bid',
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 11, 53, 15, 560532, tzinfo=utc)),
        ),
    ]
