# Generated by Django 3.0.8 on 2020-08-07 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200807_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='listed_by',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 12, 15, 5, 332046, tzinfo=utc)),
        ),
    ]
