# Generated by Django 3.0.8 on 2020-08-07 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200807_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='bid',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 12, 59, 58, 611229, tzinfo=utc)),
        ),
    ]
