# Generated by Django 3.0.8 on 2020-08-07 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200807_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitems',
            name='bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 13, 9, 10, 182951, tzinfo=utc)),
        ),
    ]
