# Generated by Django 3.0.8 on 2020-08-07 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200807_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid_id',
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 13, 50, 40, 403331, tzinfo=utc)),
        ),
    ]
