# Generated by Django 3.0.8 on 2020-08-07 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200807_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_item',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 14, 32, 39, 747590, tzinfo=utc)),
        ),
    ]
