# Generated by Django 3.0.8 on 2020-08-07 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20200807_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 14, 57, 44, 830620, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
