# Generated by Django 3.0.8 on 2020-08-07 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20200807_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 17, 43, 58, 852699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.IntegerField(),
        ),
    ]
