# Generated by Django 3.0.8 on 2020-08-08 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20200807_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='starting_bid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='starting_bid', to='auctions.bids'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 12, 55, 59, 806664, tzinfo=utc)),
        ),
    ]
