# Generated by Django 3.0.8 on 2020-08-08 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20200808_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 12, 59, 7, 520588, tzinfo=utc)),
        ),
    ]
