# Generated by Django 3.0.8 on 2020-08-08 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20200808_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 13, 1, 37, 124081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_description', to='auctions.AuctionItems'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_image', to='auctions.AuctionItems'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_item', to='auctions.AuctionItems'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_price', to='auctions.AuctionItems'),
        ),
    ]
