# Generated by Django 3.0.8 on 2020-08-08 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20200808_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 13, 3, 35, 29588, tzinfo=utc)),
        ),
    ]
