# Generated by Django 3.0.8 on 2020-08-08 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20200808_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 13, 7, 11, 539617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='starting_bid',
            field=models.IntegerField(),
        ),
    ]
