# Generated by Django 3.0.8 on 2020-08-08 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20200808_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='closed_auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('starting_bid', models.IntegerField()),
                ('image', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
                ('final_bid', models.IntegerField()),
                ('closed_date', models.DateTimeField(default=datetime.datetime(2020, 8, 8, 14, 37, 9, 456310, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 14, 37, 9, 453248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.AuctionItems'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_price', to='auctions.AuctionItems'),
        ),
    ]
