# Generated by Django 3.0.8 on 2020-08-08 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20200808_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 14, 39, 38, 893360, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_item', to='auctions.AuctionItems'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_price', to='auctions.AuctionItems'),
        ),
        migrations.AlterField(
            model_name='closed_auctions',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 14, 39, 38, 896606, tzinfo=utc)),
        ),
    ]
