# Generated by Django 3.0.8 on 2020-08-10 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20200810_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='c_item', to='auctions.AuctionItems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 14, 22, 11, 249781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='closed_auctions',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 14, 22, 11, 255492, tzinfo=utc)),
        ),
    ]
