# Generated by Django 3.0.8 on 2020-08-10 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_auto_20200810_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 14, 27, 40, 565932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='closed_auctions',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 14, 27, 40, 569331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_item',
            field=models.CharField(max_length=240),
        ),
    ]
