# Generated by Django 3.0.8 on 2020-08-10 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_auto_20200810_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 15, 8, 6, 630335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_item',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='closed_auctions',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 15, 8, 6, 637696, tzinfo=utc)),
        ),
    ]
