# Generated by Django 3.0.8 on 2020-08-12 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_auto_20200812_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='item',
        ),
        migrations.AddField(
            model_name='auctionitems',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 17, 8, 21, 559937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='closed_auctions',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 17, 8, 21, 563201, tzinfo=utc)),
        ),
    ]
