# Generated by Django 3.0.8 on 2020-08-13 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_auto_20200813_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 17, 13, 608545, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='closed_auctions',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 17, 13, 612085, tzinfo=utc)),
        ),
    ]
