# Generated by Django 3.0.8 on 2020-08-13 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0053_auto_20200813_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 15, 31, 58, 142210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='closed_auctions',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 15, 31, 58, 148980, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='image',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='price',
            field=models.IntegerField(),
        ),
    ]
