# Generated by Django 3.0.8 on 2020-08-15 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('by_user', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 8, 15, 15, 11, 36, 369803, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=350)),
                ('user', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 8, 15, 15, 11, 36, 369151, tzinfo=utc))),
                ('like', models.IntegerField()),
            ],
        ),
    ]
