# Generated by Django 3.0.8 on 2020-08-20 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200820_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='follower',
            name='following',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 12, 13, 32, 435415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 12, 13, 32, 429939, tzinfo=utc)),
        ),
    ]
