# Generated by Django 3.0.8 on 2020-08-23 10:21

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20200820_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='FollowerId',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
        migrations.AddField(
            model_name='follower',
            name='name',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 10, 21, 48, 606026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 10, 21, 48, 593877, tzinfo=utc)),
        ),
    ]
