# Generated by Django 3.0.8 on 2020-08-23 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20200823_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 10, 47, 6, 730946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='follower',
            name='users',
            field=models.ManyToManyField(to='network.Person'),
        ),
    ]
