# Generated by Django 3.0.8 on 2020-08-25 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20200825_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 15, 26, 24, 4283, tzinfo=utc)),
        ),
    ]
