# Generated by Django 3.0.8 on 2020-08-30 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_auto_20200830_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 16, 15, 56, 272418, tzinfo=utc)),
        ),
    ]
